### ISSUE TITLE
crypto.pbkdf2

### ISSUE THREAD

**Issue by bernzJ** [RamEduard/admin-lte-express#2]
The sync and async function pbkdf2 of the crypto lib requires a digest now (in the v8*+): 
https://nodejs.org/api/crypto.html#crypto_crypto_pbkdf2_password_salt_iterations_keylen_digest_callback

Should be updated [here](https://github.com/RamEduard/admin-lte-express/blob/5e1836d6ca222068ab9b9181d7df12b6a85d76ab/server/lib/auth/pass.js#L34) and [here](https://github.com/RamEduard/admin-lte-express/blob/5e1836d6ca222068ab9b9181d7df12b6a85d76ab/server/lib/auth/pass.js#L42l)

**Comment by Clonk-HTML5** [comment]
Fixed by setting 'sha512' as Digest.

in FIle:

server/lib/auth/pass.js
change line:
`crypto.pbkdf2(pwd, salt, iterations, len, function(err, hash)`
to:
`crypto.pbkdf2(pwd, salt, iterations, len, 'sha512', function(err, hash)`
